if SERVER then
    AddCSLuaFile("zeus_core/config/sh_regiments.lua")
    AddCSLuaFile("zeus_core/config/sh_zeus_config.lua")
    AddCSLuaFile("zeus_core/shared/sh_util.lua")
    AddCSLuaFile("zeus_core/client/cl_name_prompt.lua")
    AddCSLuaFile("zeus_core/client/cl_hud.lua")
    AddCSLuaFile("zeus_core/client/cl_scoreboard.lua")
    AddCSLuaFile("zeus_core/shared/sh_sam_commands.lua")

    include("zeus_core/config/sh_regiments.lua")
    include("zeus_core/config/sh_zeus_config.lua")
    include("zeus_core/shared/sh_util.lua")
    include("zeus_core/shared/sh_sam_commands.lua")
    include("zeus_core/server/sv_identity.lua")
    include("zeus_core/server/sv_xp.lua")
    include("zeus_core/server/sv_zeus_presence.lua")
    include("zeus_core/server/sv_incidents.lua")
else
    include("zeus_core/config/sh_regiments.lua")
    include("zeus_core/config/sh_zeus_config.lua")
    include("zeus_core/shared/sh_util.lua")
    include("zeus_core/shared/sh_sam_commands.lua")
    include("zeus_core/client/cl_name_prompt.lua")
    include("zeus_core/client/cl_hud.lua")
    include("zeus_core/client/cl_scoreboard.lua")
end